stages:
  - test

run-standalone-python-tests-on-windows:
  stage: test
  rules:
    - when: always
  tags:
    - unity 
    - windows
  script:
    - pip install -r requirements.txt
    - sh start_tests_Windows.sh
  artifacts:
    when: always
    expire_in: 10 days
    paths: 
      - AltUnityTesterLog.txt

run-standalone-python-tests-on-mac:
  stage: test
  rules:
    - when: always
  tags:
    - unity
    - mac
  script:
    - pip install -r requirements.txt
    - sh start_tests_Mac.sh
  artifacts:
    when: always
    expire_in: 10 days
    paths:
      - AltUnityTesterLogMac.txt
